# Bult-In Functions in Numpy

- Full
- Ones
- Zeros
- Eye
- Random.Random
- Empty

In [7]:
# 1-Full

full_num =np.full((4,5),2)
print(full_num)
# For decimel value
print(np.full((3,3),5))

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
for decimel value
[[5 5 5]
 [5 5 5]
 [5 5 5]]
