# Numpy :
- Numpy is scientific computing (package) librarry for python programming language.
- Numpy is a powerfull python programming language librarry to solve numerical problems.
- Num stand for numerical and py stand for python programming language.
- Python Numpy librarry is especially used for numeric and mathematical calculation like linear algebra, fourier transtorm, and random number capailities using numpy array.
- Numpy supports large data in the form of a multidimensional array (vector and matrix)

- One Dimensional Numpy array(1D) : It means the collection of hemogenous data in a single row(vector).

- Two Dimensional Numpy array(2D) : It means the collection of hemogenous data in lists of a list (matrix).

- Three Dimensional Numpy array(3D) : It means the collection of hemogenous data in lists of lists of a list (tensor).


In [14]:
# first we have to import numpy librarry
import numpy as np
array1 = np.array([1,2,3,4,5])
# second print and check it
print(array1)

[1 2 3 4 5]


In [15]:
# check dimensional
print(array1.ndim)

# check size of demensional
print(array1.size)

# check shape of demensional
print(array1.shape)

# check data type
print(array1.dtype)

# change the elements of Array
array1[1]=40


1
5
(5,)
int32


In [20]:
# 2D Array
array2 = np.array([[1,2,3],[6,7,8]])
print(array2.ndim)

# check data type of array
print(array2.dtype)

# check size of 2 dimensional
print(array2.size)

# check shape of 2 dimensional
print(array2.shape)

2
int32
6
(2, 3)


In [27]:
# 3D Array
array3 = np.array([[[1,2,3],[5,6,7],[3,4,5]]])
# check dimensional
print(array3.ndim)

# check size of 3D dimensional
print(array3.size)

# check shape of 3D dimensional
print(array3.shape)

# check type of arrray
type(array3)

3
9
(1, 3, 3)


numpy.ndarray

In [7]:
# Numpy slicing 
import numpy as np
first_array = np.array([[1,2,3,4],[11,12,13,14],[21,22,23,24]])
print(first_array)

first_array[:2,1:3]

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]


array([[ 2,  3],
       [12, 13]])