# Bult-In Functions in Numpy

- Full
- Ones
- Zeros
- Eye
- Random.Random
- Empty

In [14]:
# 1-Full
import numpy as np
full_num =np.full((4,5),2)
print(full_num)
# For decimel value
print(np.full((3,3),5))

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [15]:
# 2-Ones

ones_mat = np.ones((3,3))
print(ones_mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# 3-Zeros

zeros_mat = np.zeros((3,3))
print(zeros_mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# 4-Eye

eye_mat = np.eye(3,3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# 5-Random.Ramdom

random_mat = np.random.random((4,4))
print(random_mat)

[[0.99986779 0.95887358 0.73853384 0.93518468]
 [0.78862954 0.97205269 0.33168277 0.00398445]
 [0.99606888 0.57449928 0.91108939 0.99014439]
 [0.64781932 0.09547442 0.68785825 0.61261791]]


In [19]:
# 6-Empty

Empty_mat = np.empty((2,2))
print(Empty_mat)

[[1.19494240e-311 9.54898106e-313]
 [2.56761491e-312 1.78019082e-306]]
