# Numpy :
- Numpy is scientific computing (package) librarry for python programming language.
- Numpy is a powerfull python programming language librarry to solve numerical problems.
- Num stand for numerical and py stand for python programming language.
- Python Numpy librarry is especially used for numeric and mathematical calculation like linear algebra, fourier transtorm, and random number capailities using numpy array.
- Numpy supports large data in the form of a multidimensional array (vector and matrix)

- One Dimensional Numpy array(1D) : It means the collection of hemogenous data in a single row(vector).

- Two Dimensional Numpy array(2D) : It means the collection of hemogenous data in lists of a list (matrix).

- Three Dimensional Numpy array(3D) : It means the collection of hemogenous data in lists of lists of a list (tensor).


In [30]:
# first we have to import numpy librarry
import numpy as np
array1 = np.array([1,2,3,4,5])
# second print and check it
print(array1)

[1 2 3 4 5]


In [31]:
# check dimensional
print(array1.ndim)

# check size of demensional
print(array1.size)

# check shape of demensional
print(array1.shape)

# check data type
print(array1.dtype)

# change the elements of Array
array1[1]=40


1
5
(5,)
int32


In [32]:
# 2D Array
array2 = np.array([[1,2,3],[6,7,8]])
print(array2.ndim)

# check data type of array
print(array2.dtype)

# check size of 2 dimensional
print(array2.size)

# check shape of 2 dimensional
print(array2.shape)

2
int32
6
(2, 3)


In [33]:
# 3D Array
array3 = np.array([[[1,2,3],[5,6,7],[3,4,5]]])
# check dimensional
print(array3.ndim)

# check size of 3D dimensional
print(array3.size)

# check shape of 3D dimensional
print(array3.shape)

# check type of arrray
type(array3)

3
9
(1, 3, 3)


numpy.ndarray

In [34]:
# Numpy slicing 
import numpy as np
first_array = np.array([[1,2,3,4],[11,12,13,14],[21,22,23,24]])
print(first_array)

first_array[:2,1:3]

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]


array([[ 2,  3],
       [12, 13]])

# Function in Numpy

- arange
- linspace
- reshape
- ravel
- flatten
- transpose

In [35]:
# 1-Arange


import numpy as np

array_1 = np.arange(1,21)
print(array_1)

array_2 = np.arange(1,21,2)
print(array_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]


In [36]:
# 2-Linspace

linspace1 = np.linspace(1,21,3)
print(linspace1)

[ 1. 11. 21.]


In [37]:
# 3-Reshape
reshap_2D = array_1.reshape(2,10)
print(reshap_2D)


reshap_3D = array_1.reshape(1,4,5)
print(reshap_3D)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [38]:
# 4-Ravel and flatten 
# it's used for convert 2d into 1d 

ravel_1 = reshap_3D.ravel()
print(ravel_1)

ravel_2 = reshap_3D.flatten()
print(ravel_2)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [39]:
# 5-Transpose

x = np.array([[2,3,4],[5,6,7],[7,8,9]])
print(x)

#transpose
print(x.transpose())

[[2 3 4]
 [5 6 7]
 [7 8 9]]
[[2 5 7]
 [3 6 8]
 [4 7 9]]
